version: 2
jobs:
  build:
    docker:
      -image: circleci/python:3.8.8

      working_directory: ~/repo

      steps:
        - checkout

        - run:
            name: install dependecies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip intsall -r requirements.txt

        - run: 
            name: run test
            command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
              pytest -v --cov=calculator
