version: 2.1orbs
jobs:
  build:
    docker:
      -image: circleci/python:3.8.8

    working_directory: ~/repo

    steps:
      # step 1: obtain repo from Github
      - checkout
      # step 2: create virtual env and install dependecies
      - run:
          name: install dependecies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # step 3: runlinter and tests
      - run: 
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator